osx: fix c++11 build failure
* move from 'math.h' to 'cmath' header

Error:
smithdiagram.cpp:64:11: error: expected unqualified-id
  if(std::isfinite(*px))