Ci fixes (squashed)
Remove unneeded CMakeLists in bitmaps folder


Add qucs-s-spar-viewer.icns

This is required for the "build-mac-universal" and "build-mac-intel" jobs
Install libqt5charts5-dev dependency

I set up a fresh Lubuntu 24.04 on a VM and compiled the code from source using the instructions provided in the Qucs-S page. I found that to avoid the above error in the build, you need to install "libqt5charts5-dev" first. 

After that the compilation went fine. I'm not sure if it works with "libqt6charts6-dev". I'll check later.
Typo in CMakeLists


Remove unneeded include causing trouble in build appImage-Qt6

/home/runner/work/qucs_s/qucs_s/qucs-s-spar-viewer/main.cpp:28:10: fatal error: QDesktopWidget: No such file or directory
   28 | #include <QDesktopWidget>


Missing line in windows build


Patch provided by ra3xdh QtCharts


Update cmake.yml and deploy.yml

Added qt6-charts to Windows build and qt5charts to Qt5 build